---
sudo: required
dist: xenial

language: python
python:
  - "2.7"
  - "3.5"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.9.12
  - ANSIBLE_VERSION=2.9.11
  - ANSIBLE_VERSION=2.9.10
  - ANSIBLE_VERSION=2.9.9
  - ANSIBLE_VERSION=2.9.8
  - ANSIBLE_VERSION=2.9.7
  - ANSIBLE_VERSION=2.9.6
  - ANSIBLE_VERSION=2.9.5
  - ANSIBLE_VERSION=2.9.4
  - ANSIBLE_VERSION=2.9.3
  - ANSIBLE_VERSION=2.9.2
  - ANSIBLE_VERSION=2.9.1
  - ANSIBLE_VERSION=2.9.0
  - ANSIBLE_VERSION=2.8.14
  - ANSIBLE_VERSION=2.8.13
  - ANSIBLE_VERSION=2.8.12
  - ANSIBLE_VERSION=2.8.11
  - ANSIBLE_VERSION=2.8.10
  - ANSIBLE_VERSION=2.8.9
  - ANSIBLE_VERSION=2.8.8
  - ANSIBLE_VERSION=2.8.7
  - ANSIBLE_VERSION=2.8.6
  - ANSIBLE_VERSION=2.8.5
  - ANSIBLE_VERSION=2.8.4
  - ANSIBLE_VERSION=2.8.3
  - ANSIBLE_VERSION=2.8.2
  - ANSIBLE_VERSION=2.8.1
  - ANSIBLE_VERSION=2.8.0
  - ANSIBLE_VERSION=2.7.18
  - ANSIBLE_VERSION=2.7.17
  - ANSIBLE_VERSION=2.7.16
  - ANSIBLE_VERSION=2.7.15
  - ANSIBLE_VERSION=2.7.14
  - ANSIBLE_VERSION=2.7.13
  - ANSIBLE_VERSION=2.7.12
  - ANSIBLE_VERSION=2.7.11
  - ANSIBLE_VERSION=2.7.10
  - ANSIBLE_VERSION=2.7.9
  - ANSIBLE_VERSION=2.7.8
  - ANSIBLE_VERSION=2.7.7
  - ANSIBLE_VERSION=2.7.6
  - ANSIBLE_VERSION=2.7.5
  - ANSIBLE_VERSION=2.7.4
  - ANSIBLE_VERSION=2.7.3
  - ANSIBLE_VERSION=2.7.2
  - ANSIBLE_VERSION=2.7.1
  - ANSIBLE_VERSION=2.7.0
  - ANSIBLE_VERSION=2.6.20
  - ANSIBLE_VERSION=2.6.19
  - ANSIBLE_VERSION=2.6.18
  - ANSIBLE_VERSION=2.6.17
  - ANSIBLE_VERSION=2.6.16
  - ANSIBLE_VERSION=2.6.15
  - ANSIBLE_VERSION=2.6.14
  - ANSIBLE_VERSION=2.6.13
  - ANSIBLE_VERSION=2.6.12
  - ANSIBLE_VERSION=2.6.11
  - ANSIBLE_VERSION=2.6.10
  - ANSIBLE_VERSION=2.6.9
  - ANSIBLE_VERSION=2.6.8
  - ANSIBLE_VERSION=2.6.7
  - ANSIBLE_VERSION=2.6.6
  - ANSIBLE_VERSION=2.6.5
  - ANSIBLE_VERSION=2.6.4
  - ANSIBLE_VERSION=2.6.3
  - ANSIBLE_VERSION=2.6.2
  - ANSIBLE_VERSION=2.6.1
  - ANSIBLE_VERSION=2.6.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

  - >
    wget https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip -O /tmp/ubuntu-font-family-0.83.zip
    && cd /tmp
    && unzip ubuntu-font-family-0.83.zip
    && chmod 0755 ubuntu-font-family-0.83
    && cd -

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml; fi

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: "f1NHVisSHTGwUl2GJSirZty2+IkYrHnjAeyWiwjySBthy3EkblxIqm29w+bEKTNgC+8swxIcrRFEfCpSsSrYHiFovuH0XVJHnEih2LNF1aI4Lskh8K7kTBRd5GPeAoZdzpy3YX4HIdyAW6wYsSlaFI1aoEk3pHipClk0kY0azpz4wda7Ou4mRWq/XFHv5Cp5a9Qao4Ud2p2GMjdvozpYDk3nlFLPKV03emUsVH955u8bz+3Mfa/8rR1nYAcLsv6IvR96rRAnHDOFobyrV+h3X7xkmuVZNjLss3NpFYP51mIdzrARMSghr+P1vzZSeW3mkwVel90HGRJ07ORKbyHzvdLi8XHpH0zdbid+wF6HAYpaMW8A7c+f0qjmThVe/0DrNNHnR5C54h8hLg3jagE0VWstoImiomBSDv4JWe5wQIltjcruVTwMDIqyZ2z6CyBtE1s2zBX2q+1Jj8LlZladFrLB67tmV4TznvSJ/sxhZnKg91wolycbcEvIUvcV4TjtVZZ530/8p6Jj4VPyI+DYBS+wfHSDUMpIQr9NncQaNuVIwFtqdK0yjG1h0WY3F5zRFj8Rc5o0WZPhldRrQI2uDo6gPlK0uVR8VI4P1mvac9mQOxcPUIdRuczP7dx5te9FAPCemPqojcfMa+HAnXn82VraxTHDfL6tG5wrbeZegL4="
