---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/vars/main.yml"
    - name: include tasks
      include: "{{ playbook_dir }}/tasks/pre.yml"
  roles:
    - ../../../
